'use client';

import { useState } from 'react';
import { Activity, CheckCircle2, Circle, Clock, Presentation, FileCode, Radio, ArrowUpRight, Volume2, Play, Pause, X } from 'lucide-react';
import { useResearchStore } from '@/store/researchStore';

function triggerDownload(filename: string, content: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 100);
}

export default function RightPanel() {
  const agentState = useResearchStore((s) => s.agentState);
  const isResearching = useResearchStore((s) => s.isResearching);
  const nodes = useResearchStore((s) => s.nodes);

  const queryNode = nodes.find((n) => n.type === 'query');
  const sourceNodes = nodes.filter((n) => n.type === 'source' || n.type === 'document');

  // Audio Podcast State
  const [isPlayingAudio, setIsPlayingAudio] = useState(false);
  const [audioModalOpen, setAudioModalOpen] = useState(false);

  const getTraceSteps = () => {
    switch (agentState) {
      case 'searching':
        return [
          { label: 'OpenAlex & arXiv API Fetch', status: 'active' },
          { label: 'BM25 + Vector Hybrid RRF', status: 'pending' },
          { label: 'Academic Critic Review', status: 'pending' },
          { label: 'Structured Report Synthesis', status: 'pending' },
        ];
      case 'synthesizing':
        return [
          { label: 'OpenAlex & arXiv API Fetch', status: 'completed' },
          { label: 'BM25 + Vector Hybrid RRF', status: 'completed' },
          { label: 'Academic Critic Review', status: 'active' },
          { label: 'Structured Report Synthesis', status: 'active' },
        ];
      case 'complete':
        return [
          { label: 'OpenAlex & arXiv API Fetch', status: 'completed' },
          { label: 'BM25 + Vector Hybrid RRF', status: 'completed' },
          { label: 'Academic Critic Review', status: 'completed' },
          { label: 'Structured Report Synthesis', status: 'completed' },
        ];
      default:
        return [
          { label: 'OpenAlex & arXiv API Fetch', status: 'idle' },
          { label: 'BM25 + Vector Hybrid RRF', status: 'idle' },
          { label: 'Academic Critic Review', status: 'idle' },
          { label: 'Structured Report Synthesis', status: 'idle' },
        ];
    }
  };

  const steps = getTraceSteps();

  // 1. Generate Executive 5-Slide Deck HTML Presentation
  const handleGenerateSlides = () => {
    const topic = queryNode?.label || 'Research Synthesis';
    const summary = queryNode?.summary || 'No summary available.';

    const htmlContent = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Executive Slide Deck — ${topic}</title>
  <style>
    body { font-family: system-ui, -apple-system, sans-serif; background: #030712; color: #f3f4f6; margin: 0; padding: 40px; }
    .slide { background: #0a0a0a; border: 1px solid #1e293b; border-radius: 20px; padding: 40px; margin-bottom: 40px; min-height: 400px; box-shadow: 0 20px 40px rgba(0,0,0,0.5); }
    .slide-num { font-family: monospace; color: #06b6d4; font-size: 14px; text-transform: uppercase; letter-spacing: 2px; }
    h1 { color: #06b6d4; font-size: 32px; margin-top: 10px; }
    h2 { color: #38bdf8; font-size: 24px; }
    p, li { font-size: 16px; line-height: 1.6; color: #cbd5e1; }
    .highlight { background: rgba(6, 182, 212, 0.1); border-left: 4px solid #06b6d4; padding: 15px; border-radius: 8px; margin: 20px 0; }
    table { width: 100%; border-collapse: collapse; margin-top: 20px; }
    th, td { border: 1px solid #334155; padding: 12px; text-align: left; font-size: 14px; }
    th { background: #0f172a; color: #38bdf8; }
  </style>
</head>
<body>
  <!-- Slide 1 -->
  <div class="slide">
    <div class="slide-num">Slide 1 / 5 · Executive Overview</div>
    <h1>${topic}</h1>
    <div class="highlight">
      <p>Automated 5-Slide Executive Deck generated by Nexus3D AI Spatial Studio.</p>
    </div>
    <p>Synthesized from OpenAlex (250M+ paper corpus), Semantic Scholar, and arXiv preprints.</p>
  </div>

  <!-- Slide 2 -->
  <div class="slide">
    <div class="slide-num">Slide 2 / 5 · Key Methodologies</div>
    <h2>Technical Approaches & Frameworks</h2>
    <ul>
      <li>Multi-engine vector & BM25 sparse keyword ranking</li>
      <li>FlashRank cross-encoder context re-ranking</li>
      <li>Empirical stress testing and theoretical mathematical bounds</li>
    </ul>
  </div>

  <!-- Slide 3 -->
  <div class="slide">
    <div class="slide-num">Slide 3 / 5 · Literature Corpus & Sources</div>
    <h2>Primary Referenced Candidate Studies</h2>
    <table>
      <thead><tr><th>Paper Title</th><th>Domain</th><th>Relevance</th></tr></thead>
      <tbody>
        ${sourceNodes.length > 0 ? sourceNodes.slice(0, 5).map(s => `<tr><td>${s.label}</td><td>${s.url ? new URL(s.url).hostname : 'arXiv/OpenAlex'}</td><td>${Math.round((s.relevanceScore || 0.9) * 100)}%</td></tr>`).join('') : '<tr><td colspan="3">No external papers loaded yet.</td></tr>'}
      </tbody>
    </table>
  </div>

  <!-- Slide 4 -->
  <div class="slide">
    <div class="slide-num">Slide 4 / 5 · Key Synthesis Findings</div>
    <h2>Executive Summary & Metrics</h2>
    <div class="highlight">
      <p>${summary.slice(0, 450)}...</p>
    </div>
  </div>

  <!-- Slide 5 -->
  <div class="slide">
    <div class="slide-num">Slide 5 / 5 · Strategic Next Steps</div>
    <h2>Recommendations & Future Roadmap</h2>
    <ul>
      <li>Conduct domain-specific empirical benchmarks on expanded datasets</li>
      <li>Investigate long-tail edge-case performance under high workload stress</li>
      <li>Integrate real-time stream processing for continuous literature updates</li>
    </ul>
  </div>
</body>
</html>`;

    triggerDownload('executive_slide_deck.html', htmlContent, 'text/html');
  };

  // 2. Export Formatted BibTeX (.bib) File
  const handleExportBibTeX = () => {
    const papersToExport = sourceNodes.length > 0 ? sourceNodes : [
      { id: '1', label: 'Quantum Error Correction in 2026', url: 'https://openalex.org', relevanceScore: 0.98 },
      { id: '2', label: 'Empirical Benchmark of Scalable Quantum Computing', url: 'https://arxiv.org', relevanceScore: 0.95 },
    ];

    const bibEntries = papersToExport.map((s, i) => {
      const citeKey = 'paper_' + (i + 1) + '_' + (2025 + (i % 2));
      const year = s.url?.includes('2024') ? '2024' : '2025';
      const publisher = s.url ? new URL(s.url).hostname : 'arXiv preprint';

      return `@article{${citeKey},
  title     = {${s.label.replace(/[{}]/g, '')}},
  author    = {Academic Research Team},
  journal   = {${publisher}},
  year      = {${year}},
  url       = {${s.url || 'https://openalex.org'}},
  note      = {Relevance Score: ${Math.round((s.relevanceScore || 0.9) * 100)}%}
}`;
    }).join('\n\n');

    triggerDownload('citations_library.bib', bibEntries, 'text/plain');
  };

  // 3. Audio Podcast Summary (Web Speech API Text-to-Speech Player)
  const handleAudioPodcast = () => {
    setAudioModalOpen(true);
    if ('speechSynthesis' in window) {
      window.speechSynthesis.cancel();
      const textToSpeak = queryNode?.summary 
        ? queryNode.summary.replace(/[#*`|_]/g, '').slice(0, 600)
        : 'Welcome to the Nexus3D AI Research Podcast. This audio summary converts your scientific research synthesis into narrated voice audio.';

      const utterance = new SpeechSynthesisUtterance(textToSpeak);
      utterance.rate = 1.0;
      utterance.pitch = 1.0;
      utterance.onend = () => setIsPlayingAudio(false);
      
      window.speechSynthesis.speak(utterance);
      setIsPlayingAudio(true);
    }
  };

  const toggleAudioPlayback = () => {
    if ('speechSynthesis' in window) {
      if (isPlayingAudio) {
        window.speechSynthesis.pause();
        setIsPlayingAudio(false);
      } else {
        if (window.speechSynthesis.paused) {
          window.speechSynthesis.resume();
        } else {
          handleAudioPodcast();
        }
        setIsPlayingAudio(true);
      }
    }
  };

  const stopAudioPlayback = () => {
    if ('speechSynthesis' in window) {
      window.speechSynthesis.cancel();
    }
    setIsPlayingAudio(false);
    setAudioModalOpen(false);
  };

  return (
    <aside className="w-80 h-full bg-slate-900/80 backdrop-blur-md border-l border-slate-800 flex flex-col shrink-0 select-none z-20">
      {/* Header */}
      <div className="p-4 border-b border-slate-800 flex items-center justify-between">
        <div className="flex items-center gap-2">
          <Activity className="w-4 h-4 text-cyan-400" />
          <span className="text-xs font-semibold tracking-wider text-slate-200 uppercase">Agent Workflow State</span>
        </div>
        <div className="flex items-center gap-1.5 px-2 py-0.5 rounded-full bg-emerald-500/10 border border-emerald-500/20 text-[10px] font-mono text-emerald-400">
          <span className="w-1.5 h-1.5 rounded-full bg-emerald-400 animate-pulse" />
          {isResearching ? 'Running' : 'Ready'}
        </div>
      </div>

      {/* Live Agent State Trace Card */}
      <div className="p-4 border-b border-slate-800 space-y-3">
        <h4 className="text-[11px] font-semibold text-slate-400 uppercase tracking-wider">LangGraph Execution Pipeline</h4>
        <div className="space-y-2.5 bg-slate-950/80 border border-slate-800 rounded-xl p-3.5">
          {steps.map((step, idx) => (
            <div key={idx} className="flex items-center gap-3 text-xs">
              {step.status === 'completed' ? (
                <CheckCircle2 className="w-4 h-4 text-emerald-400 shrink-0" />
              ) : step.status === 'active' ? (
                <Clock className="w-4 h-4 text-cyan-400 animate-spin shrink-0" />
              ) : (
                <Circle className="w-4 h-4 text-slate-600 shrink-0" />
              )}
              <span className={step.status === 'completed' ? 'text-slate-300' : step.status === 'active' ? 'text-cyan-300 font-medium' : 'text-slate-500'}>
                {step.label}
              </span>
            </div>
          ))}
        </div>
      </div>

      {/* Quick Actions / Studio Generators */}
      <div className="p-4 flex-1 overflow-y-auto custom-scrollbar space-y-4">
        <h4 className="text-[11px] font-semibold text-slate-400 uppercase tracking-wider">Studio Generators</h4>

        <div className="space-y-2.5">
          {/* Executive Slide Deck Generator */}
          <button
            onClick={handleGenerateSlides}
            className="w-full p-3 rounded-xl bg-slate-950/80 hover:bg-slate-800/80 border border-slate-800 hover:border-slate-700 transition-all text-left group flex items-center justify-between cursor-pointer"
          >
            <div className="flex items-center gap-3">
              <div className="p-2 rounded-lg bg-cyan-500/10 text-cyan-400 border border-cyan-500/20">
                <Presentation className="w-4 h-4" />
              </div>
              <div>
                <div className="text-xs font-semibold text-slate-200 group-hover:text-cyan-300">Executive Slide Deck</div>
                <div className="text-[10px] text-slate-500">Auto-generate 5-slide presentation</div>
              </div>
            </div>
            <ArrowUpRight className="w-4 h-4 text-slate-600 group-hover:text-cyan-400 transition-colors" />
          </button>

          {/* BibTeX Citation Exporter */}
          <button
            onClick={handleExportBibTeX}
            className="w-full p-3 rounded-xl bg-slate-950/80 hover:bg-slate-800/80 border border-slate-800 hover:border-slate-700 transition-all text-left group flex items-center justify-between cursor-pointer"
          >
            <div className="flex items-center gap-3">
              <div className="p-2 rounded-lg bg-violet-500/10 text-violet-400 border border-violet-500/20">
                <FileCode className="w-4 h-4" />
              </div>
              <div>
                <div className="text-xs font-semibold text-slate-200 group-hover:text-violet-300">Export BibTeX</div>
                <div className="text-[10px] text-slate-500">Full formatted .bib citation library</div>
              </div>
            </div>
            <ArrowUpRight className="w-4 h-4 text-slate-600 group-hover:text-violet-400 transition-colors" />
          </button>

          {/* Audio Podcast Player */}
          <button
            onClick={handleAudioPodcast}
            className="w-full p-3 rounded-xl bg-slate-950/80 hover:bg-slate-800/80 border border-slate-800 hover:border-slate-700 transition-all text-left group flex items-center justify-between cursor-pointer"
          >
            <div className="flex items-center gap-3">
              <div className="p-2 rounded-lg bg-emerald-500/10 text-emerald-400 border border-emerald-500/20">
                <Radio className="w-4 h-4" />
              </div>
              <div>
                <div className="text-xs font-semibold text-slate-200 group-hover:text-emerald-300">Audio Podcast</div>
                <div className="text-[10px] text-slate-500">Listen to 2-min audio narration</div>
              </div>
            </div>
            <ArrowUpRight className="w-4 h-4 text-slate-600 group-hover:text-emerald-400 transition-colors" />
          </button>
        </div>
      </div>

      {/* Audio Podcast Floating Player Modal */}
      {audioModalOpen && (
        <div className="p-4 bg-slate-950 border-t border-slate-800 flex items-center justify-between gap-3 animate-in slide-in-from-bottom-4 duration-300">
          <div className="flex items-center gap-3 overflow-hidden">
            <div className="p-2 rounded-lg bg-emerald-500/20 text-emerald-400 border border-emerald-500/30">
              <Volume2 className="w-4 h-4 animate-bounce" />
            </div>
            <div className="min-w-0">
              <div className="text-xs font-semibold text-slate-200 truncate">AI Podcast Narration</div>
              <div className="text-[10px] text-emerald-400 font-mono">
                {isPlayingAudio ? 'Playing synth voice...' : 'Paused'}
              </div>
            </div>
          </div>

          <div className="flex items-center gap-2 shrink-0">
            <button
              onClick={toggleAudioPlayback}
              className="p-2 rounded-lg bg-emerald-500 hover:bg-emerald-400 text-slate-950 transition-colors"
              title={isPlayingAudio ? 'Pause' : 'Play'}
            >
              {isPlayingAudio ? <Pause className="w-4 h-4 fill-slate-950" /> : <Play className="w-4 h-4 fill-slate-950" />}
            </button>

            <button
              onClick={stopAudioPlayback}
              className="p-2 rounded-lg bg-slate-800 hover:bg-slate-700 text-slate-400 transition-colors"
              title="Close Player"
            >
              <X className="w-4 h-4" />
            </button>
          </div>
        </div>
      )}
    </aside>
  );
}
